"""Independent, reviewable source definitions for generalization-sft-v1."""

from __future__ import annotations

from dataclasses import dataclass

DATASET_NAME = "generalization-sft"
DATASET_VERSION = "generalization-sft-v1"
SOURCE_VERSION = 1
PROMPT_FORMS = (
    "direct_definition", "scenario", "comparison", "misconception_correction",
    "why", "how", "command_oriented", "example_request",
)
REQUIRED_FAMILIES = (
    "byteseed_identity", "byteseed_capabilities_limitations",
    "stack_fundamentals", "queue_fundamentals", "stack_queue_comparison",
    "overfitting", "underfitting", "fit_contrast", "dsa_study_planning",
    "local_workflow", "cuda_troubleshooting", "checkpoint_git_hygiene",
)


@dataclass(frozen=True)
class Lesson:
    lesson_id: str
    family: str
    focus: str
    fact: str
    situation: str
    misconception: str
    example: str


def _family(family: str, rows: tuple[tuple[str, str, str, str, str, str], ...]) -> tuple[Lesson, ...]:
    return tuple(Lesson(slug, family, focus, fact, situation, wrong, example)
                 for slug, focus, fact, situation, wrong, example in rows)


LESSONS = (
    *_family("byteseed_identity", (
        ("identity-project", "ByteSeed's project identity",
         "ByteSeed is a small decoder-only GPT-style Transformer implemented in PyTorch.",
         "Someone sees the repository name and asks what kind of software it is.",
         "ByteSeed is a hosted commercial assistant.",
         "ByteSeed is a small local GPT-style learning project built with PyTorch."),
        ("identity-local", "ByteSeed's local scope",
         "ByteSeed is designed to run locally rather than as a hosted service.",
         "A learner wants to experiment without sending prompts to a remote endpoint.",
         "ByteSeed requires a cloud API for every response.",
         "After local setup, the terminal chat runs on the user's computer."),
        ("identity-architecture", "ByteSeed's model type",
         "ByteSeed uses a causal decoder-only Transformer that predicts the next token.",
         "A reader wants to place the project within common language-model architectures.",
         "ByteSeed is an encoder-only classifier.",
         "Its embeddings pass through causal Transformer blocks before the language-model head."),
        ("identity-implementation", "the direct PyTorch implementation",
         "The Transformer components are implemented directly in PyTorch for inspection and experiments.",
         "A student wants code where attention, residual blocks, and generation are visible.",
         "ByteSeed only wraps a downloaded production model.",
         "The repository exposes its attention and Transformer blocks in ordinary PyTorch code."),
        ("identity-purpose", "ByteSeed's intended purpose",
         "ByteSeed exists for learning, controlled experiments, and local model development.",
         "A maintainer explains why a small model can still be useful.",
         "ByteSeed is intended to replace a production assistant.",
         "A learner can study model code, training flow, evaluation, and inference behavior."),
        ("identity-scale", "ByteSeed's small scale",
         "ByteSeed is intentionally tiny compared with modern production language models.",
         "A user expects broad knowledge because the project uses a GPT-style architecture.",
         "Using a Transformer makes ByteSeed equivalent to a large commercial model.",
         "Its compact configuration is approachable, but its response quality is limited."),
        ("identity-experimental", "ByteSeed's experimental status",
         "ByteSeed is an experimental learning model, not production-ready software.",
         "A developer asks whether an important workflow should trust every generated answer.",
         "Every ByteSeed response is guaranteed to be safe and correct.",
         "Generated guidance should be checked before consequential use."),
        ("identity-boundary", "ByteSeed's interaction boundary",
         "ByteSeed generates text from local context; it does not automatically browse, read private files, or act on the system.",
         "A user asks it to fetch live facts and change files without tools.",
         "ByteSeed can silently access the internet and control the computer.",
         "It can explain a command, but the user runs and verifies it."),
    )),
    *_family("byteseed_capabilities_limitations", (
        ("capability-dsa", "concise DSA explanations",
         "ByteSeed is intended to give short explanations of basic DSA concepts such as stacks and queues.",
         "A beginner needs a compact reminder before an introductory problem.",
         "ByteSeed guarantees expert solutions for every algorithmic problem.",
         "It can summarize FIFO or LIFO behavior, while difficult solutions still need verification."),
        ("capability-study", "the limited scope of ByteSeed study-planning help",
         "ByteSeed can suggest a short schedule with review, practice, and recap time.",
         "A learner has less than an hour and wants a realistic practice structure.",
         "ByteSeed can manage an entire curriculum without user judgment.",
         "It can divide a session into review, problem solving, and mistake analysis."),
        ("capability-workflow", "basic ByteSeed workflow guidance",
         "ByteSeed can describe project steps such as entering the repository, activating an environment, and launching chat.",
         "A contributor remembers the project but not the normal local workflow.",
         "ByteSeed can configure any machine automatically.",
         "It can provide local commands while the user checks paths and environment details."),
        ("capability-cuda", "basic PyTorch CUDA troubleshooting",
         "ByteSeed can suggest targeted checks for common CUDA-detection problems in PyTorch.",
         "Torch uses CPU even though the user expected an NVIDIA GPU.",
         "ByteSeed can repair drivers and hardware by itself.",
         "It can point to the environment, PyTorch build, driver, and torch.cuda checks."),
        ("capability-checkpoints", "checkpoint hygiene guidance",
         "ByteSeed can explain why generated checkpoint binaries normally stay outside ordinary Git history.",
         "A developer is unsure whether a large artifact belongs beside source code.",
         "All checkpoint sharing is forbidden.",
         "It can distinguish Git history from release assets, registries, and artifact storage."),
        ("capability-short", "short technical answers",
         "ByteSeed targets concise, narrow technical responses rather than exhaustive expert advice.",
         "A user asks for a quick definition and one practical example.",
         "ByteSeed is a complete authority on every technical domain.",
         "A useful answer states the core rule, gives a small example, and avoids unsupported detail."),
        ("capability-browsing", "the absence of automatic browsing",
         "ByteSeed cannot verify live facts or browse websites without a separately provided tool.",
         "A question depends on today's driver release or another changing fact.",
         "ByteSeed always knows current online information.",
         "The answer should state the limit and ask the user to verify the current source."),
        ("capability-reliability", "the model's reliability boundary",
         "ByteSeed outputs may be incomplete or wrong, so important steps need independent checking.",
         "A generated command would alter an important development environment.",
         "A plausible ByteSeed answer is automatically correct.",
         "Inspect the command and relevant documentation before executing it."),
    )),
    *_family("stack_fundamentals", (
        ("stack-lifo", "last-in-first-out stack ordering",
         "A stack removes the most recently added item first, which is LIFO order.",
         "Blocks red, blue, then green are placed on one pile.",
         "A stack removes the oldest item first.",
         "Green leaves before blue and red because it was added last."),
        ("stack-push", "the stack push operation",
         "Push adds a new item to the top of a stack.",
         "A stack contains 2 and 5, then the program pushes 8.",
         "Push removes the bottom item.",
         "After push(8), the new top is 8 and older values remain below it."),
        ("stack-pop", "the stack pop operation",
         "Pop removes and returns the current top item of a nonempty stack.",
         "A stack has A at the bottom and C at the top when pop is called.",
         "Pop removes whichever item entered first.",
         "The operation returns C and exposes the item beneath it."),
        ("stack-peek", "reading the top of a stack",
         "Peek or top reads the newest stack item without removing it.",
         "A program must inspect the pending item but keep the stack unchanged.",
         "Peeking always deletes the top element.",
         "A peek returns the top value while the stack size stays the same."),
        ("stack-plates", "a plate-pile stack analogy",
         "A plate pile illustrates a stack because the last plate placed on top is taken first.",
         "Three clean plates are placed one after another.",
         "A plate pile naturally serves the bottom plate first.",
         "The newest top plate is removed without disturbing the plates below."),
        ("stack-undo", "using a stack for undo history",
         "Undo history uses a stack so the latest completed action is reversed first.",
         "A user types text, changes its color, then moves it before pressing undo.",
         "Undo should reverse the oldest edit before the newest one.",
         "The move is undone first, followed by the color change."),
        ("stack-calls", "nested function-call return order",
         "A call stack keeps active frames so the most recent call returns first.",
         "Function main calls parse, and parse calls scan.",
         "main must return before scan finishes.",
         "scan completes first, then parse, then main."),
        ("stack-empty", "safe empty-stack handling",
         "Code should check whether a stack is empty before pop when underflow is possible.",
         "Input may request removal even when no items were pushed.",
         "Popping an empty stack always produces a meaningful item.",
         "The implementation should reject or handle the empty case according to its API."),
    )),
    *_family("queue_fundamentals", (
        ("queue-fifo", "first-in-first-out queue ordering",
         "A queue removes the earliest enqueued item first, which is FIFO order.",
         "Requests 14, 15, then 16 enter a service queue.",
         "A queue takes the newest arrival first.",
         "Request 14 leaves before 15 and 16 because it arrived first."),
        ("queue-enqueue", "the enqueue operation",
         "Enqueue adds an item at the back of a queue.",
         "A queue holds A then B, and C arrives next.",
         "Enqueue removes the item at the front.",
         "C joins behind B while A remains at the front."),
        ("queue-dequeue", "the dequeue operation",
         "Dequeue removes and returns the front item of a nonempty queue.",
         "Jobs X, Y, and Z wait in arrival order when one job is taken.",
         "Dequeue returns the latest job Z.",
         "The operation returns X, leaving Y at the front."),
        ("queue-front", "reading the front of a queue",
         "Front or peek reads the next queue item without removing it.",
         "A scheduler inspects the next job before deciding whether to run it.",
         "Looking at the front must dequeue the item.",
         "The front value can be inspected while the queue length stays unchanged."),
        ("queue-line", "a first-come service-line analogy",
         "A fair service line behaves like a queue because earlier arrivals are served earlier.",
         "Noor, Isha, then Ravi join a ticket counter.",
         "The most recent arrival should be served first.",
         "Noor is served first under ordinary first-come ordering."),
        ("queue-printer", "using a queue for printer jobs",
         "A basic printer queue processes waiting jobs in arrival order.",
         "Three ordinary jobs arrive while the printer is busy.",
         "The printer should take the last submitted job first.",
         "The oldest waiting job runs next unless a priority policy changes the order."),
        ("queue-bfs", "using a queue in breadth-first search",
         "Breadth-first search uses a queue to expand nodes in first-discovered order.",
         "A traversal must visit one distance layer before the next.",
         "Breadth-first search relies on last-in-first-out removal.",
         "New nodes join the back while earlier discoveries leave from the front."),
        ("queue-empty", "safe empty-queue handling",
         "Code should handle an empty queue before dequeue when underflow is possible.",
         "A worker asks for a task after the final queued job finishes.",
         "Dequeue on an empty queue always returns a valid job.",
         "The API should report or handle the empty state rather than inventing an item."),
    )),
    *_family("stack_queue_comparison", (
        ("compare-removal", "stack and queue removal order",
         "A stack removes the newest item first, while a queue removes the oldest item first.",
         "Items K, L, and M are inserted into both structures in that order.",
         "Stacks and queues choose the same next item.",
         "The stack yields M, but the queue yields K."),
        ("compare-operations", "stack and queue operation names",
         "Stacks use push and pop at the top; queues enqueue at the back and dequeue at the front.",
         "A developer is translating pseudocode that mixes pop with dequeue.",
         "Enqueue and pop describe the same end behavior.",
         "Push/pop describe stack access; enqueue/dequeue describe queue access."),
        ("compare-undo-service", "choosing between undo and service ordering",
         "Undo history fits a stack, while first-come service fits a queue.",
         "One feature reverses recent edits and another processes requests by arrival time.",
         "Both features should use newest-first removal.",
         "Recent edits need LIFO; arriving requests normally need FIFO."),
        ("compare-top-front", "the stack top and queue front",
         "A stack exposes its newest item at the top; a queue exposes its oldest item at the front.",
         "Two containers hold the same insertions but report different next values.",
         "The queue front is always the newest item.",
         "After inserting 1 then 2, stack top is 2 and queue front is 1."),
        ("compare-scheduling", "structure choice for pending work",
         "Use a queue for arrival-order work and a stack when the latest item must be revisited first.",
         "A program needs containers for support tickets and backtracking choices.",
         "Any pending-work problem should use a stack.",
         "Tickets suit a queue; the latest backtracking choice suits a stack."),
        ("compare-fairness", "fair arrival order versus recency order",
         "Queue order emphasizes first-come service, while stack order emphasizes recency.",
         "A policy chooses between fairness by arrival and returning to the latest state.",
         "LIFO is the ordinary fair-line policy.",
         "FIFO serves arrivals fairly; LIFO revisits the newest item."),
        ("compare-shared", "what stacks and queues share",
         "Both store ordered collections, but their removal ends and ordering rules differ.",
         "A beginner assumes different removal order means they have nothing in common.",
         "Stacks store items but queues do not.",
         "Both add, inspect, and remove items under different access policies."),
        ("compare-choice", "selecting a stack or queue",
         "Choose a stack for last-added-first behavior and a queue for first-added-first behavior.",
         "A specification states only which inserted item must be processed next.",
         "The names of stored values determine the data structure.",
         "The required removal order, not item names, determines the choice."),
    )),
    *_family("overfitting", (
        ("overfit-gap", "the training-validation performance gap",
         "Overfitting often appears as strong training performance with much weaker validation performance.",
         "Training loss is low, but validation loss remains high.",
         "Poor results on both splits are the usual sign of overfitting.",
         "The large split gap suggests the model learned training-specific detail."),
        ("overfit-memory", "memorization without generalization",
         "A model overfits when it memorizes training examples but fails on unfamiliar inputs.",
         "Exact practice questions work while modestly changed questions fail.",
         "Memorizing examples is underfitting.",
         "This is overfitting because recall did not transfer to new wording."),
        ("overfit-curves", "validation loss rising during training",
         "Falling training loss alongside rising validation loss is a common overfitting warning.",
         "Later epochs improve training while the validation metric worsens.",
         "More training always improves generalization.",
         "The best validation point may occur before the final epoch."),
        ("overfit-complexity", "excess capacity relative to data",
         "A flexible model can overfit a small dataset by fitting noise and accidental detail.",
         "A large model is trained on only a few narrow examples.",
         "More capacity can never hurt validation behavior.",
         "Capacity must be judged with data scale and validation evidence."),
        ("overfit-leakage", "leakage and misleading evaluation",
         "Evaluation overlap can make memorization look like generalization, so clean holdouts are needed.",
         "The same wording appears in training and a reported benchmark.",
         "A high score on copied prompts proves unseen generalization.",
         "That score is retention until an untouched holdout is evaluated."),
        ("overfit-regularization", "responses to overfitting",
         "Responses may include more clean data, regularization, early stopping, or lower capacity.",
         "Validation quality declines after training continues beyond its useful point.",
         "The only remedy is to make the model larger.",
         "Early stopping at the best validation state is one practical option."),
        ("overfit-validation", "using validation data to detect overfitting",
         "Validation data shows whether training improvements transfer beyond optimized examples.",
         "A team reviews only training accuracy before choosing a checkpoint.",
         "Training metrics alone establish generalization.",
         "A separate validation metric can expose a growing generalization gap."),
        ("overfit-diversity", "varied clean examples as a defense",
         "Meaningful variation in clean examples reduces reliance on one memorized wording.",
         "A model answers one template but fails equivalent requests phrased differently.",
         "Punctuation-only copies provide broad generalization evidence.",
         "Different scenarios and formulations teach a concept more broadly."),
    )),
    *_family("underfitting", (
        ("underfit-both", "weak training and validation performance",
         "Underfitting usually produces weak performance on both training and validation data.",
         "A model misses examples it saw and also misses new ones.",
         "This train-and-validation failure is overfitting.",
         "The model has not captured the pattern, which indicates underfitting."),
        ("underfit-capacity", "insufficient model capacity",
         "A model may underfit when it is too simple to represent the important pattern.",
         "A linear rule is used for data with strong nonlinear structure.",
         "An overly simple model is memorizing the training set.",
         "Insufficient capacity can keep error high on every split."),
        ("underfit-training", "insufficient effective training",
         "Too little useful training can cause underfitting because available patterns remain unlearned.",
         "Training stops almost immediately while loss is still high.",
         "Stopping before learning completes is overfitting.",
         "Appropriate additional training may improve both splits."),
        ("underfit-features", "inadequate input features",
         "A model can underfit when inputs omit information needed to explain the target.",
         "A predictor receives only an unrelated feature and performs poorly everywhere.",
         "Missing useful features create memorization.",
         "Better relevant features may allow the main relationship to be learned."),
        ("underfit-regularization", "excessive regularization",
         "Regularization that is too strong can prevent fitting even the training data.",
         "A severe penalty keeps weights near zero and both split errors high.",
         "Stronger regularization always fixes every fit problem.",
         "Reducing an excessive penalty may restore enough flexibility."),
        ("underfit-bias", "high-bias behavior",
         "Underfitting is often called high bias because model assumptions are too restrictive.",
         "Predictions follow an overly rigid rule despite clear sample structure.",
         "High bias means memorizing individual records.",
         "The rigid rule causes systematic errors on training and validation cases."),
        ("underfit-diagnosis", "checking training error before labeling a fit problem",
         "High training error is a key signal to inspect before blaming a validation-only problem.",
         "A developer sees poor validation quality but has not checked training performance.",
         "Validation error alone proves overfitting.",
         "Training error separates a broad fit failure from a generalization gap."),
        ("underfit-remedies", "choosing a remedy from the diagnosed limitation",
         "Remedies may include suitable capacity, better features, or sufficient training.",
         "Both metrics remain weak under a very limited setup.",
         "The remedy is always to stop training earlier.",
         "Target the identified capacity, feature, or optimization limitation."),
    )),
    *_family("fit_contrast", (
        ("contrast-signals", "the main fit diagnostic",
         "Overfitting has a train-validation gap; underfitting has poor training and validation performance.",
         "Two runs have weak validation scores, but only one also has weak training scores.",
         "Any weak validation score means overfitting.",
         "Strong train with weak validation suggests overfitting; weakness on both suggests underfitting."),
        ("contrast-memory", "memorization versus failure to learn",
         "Overfitting memorizes narrow detail; underfitting fails to learn enough of the training pattern.",
         "One model repeats seen answers; another misses seen answers too.",
         "Memorization and failure to fit are the same problem.",
         "The first behavior is overfitting and the second is underfitting."),
        ("contrast-capacity", "capacity in the two fit problems",
         "Too much effective flexibility can support overfitting; too little can cause underfitting.",
         "A team compares an oversized model on little data with an overly rigid model.",
         "Increasing capacity always reduces both problems.",
         "Capacity must be balanced against data and validation behavior."),
        ("contrast-time", "training time and fit",
         "Too little training can underfit, while training past the best validation point can overfit.",
         "A run is checked near initialization and long after validation starts degrading.",
         "More epochs remove underfitting without any risk.",
         "Choose duration using training progress and validation evidence."),
        ("contrast-remedies", "different remedies for the two fit problems",
         "Overfitting may need regularization or varied data; underfitting may need capacity, features, or training.",
         "One remedy is proposed for runs with opposite diagnostic patterns.",
         "Early stopping is the universal fix for poor fitting.",
         "The remedy follows whether there is a generalization gap or failure to fit."),
        ("contrast-curves", "reading learning curves",
         "Diverging curves suggest overfitting, while persistently high errors suggest underfitting.",
         "Training and validation losses are plotted for two experiments.",
         "Only the final validation number is needed to classify both.",
         "The relationship between both curves provides the evidence."),
        ("contrast-new", "behavior on seen and unseen data",
         "An overfit model can succeed on seen data and fail on new data; an underfit model often fails on both.",
         "Answers are compared on rehearsed and fresh formulations.",
         "Failure on a fresh prompt automatically means underfitting.",
         "Seen-prompt performance distinguishes memorization from insufficient fit."),
        ("contrast-terms", "using fit terminology precisely",
         "Call a model overfit when training success fails to transfer, and underfit when training patterns are not learned.",
         "A report labels every weak output as overfitting without checking training.",
         "Overfitting is a synonym for any low-quality prediction.",
         "The labels describe different training-versus-validation relationships."),
    )),
    *_family("dsa_study_planning", (
        ("plan-twenty", "a micro-session for stack operation review",
         "Use about 5 minutes to recall the rule, 10 for one problem, and 5 to review mistakes.",
         "A learner has twenty minutes before another class.",
         "A short session should contain only passive reading.",
         "Review LIFO, solve one operation trace, then note the error pattern."),
        ("plan-thirty", "a half-hour queue practice block",
         "A balanced 30-minute session can use 5 minutes for recall, 20 for practice, and 5 for recap.",
         "A learner wants useful queue practice in half an hour.",
         "Thirty minutes is too short for deliberate problem solving.",
         "Review FIFO, trace two queue examples, and record one takeaway."),
        ("plan-forty", "a linked-list pointer practice block",
         "Use a short concept review, a larger solving block, and a final error review within 40 minutes.",
         "A student is weak on linked-list pointer updates.",
         "Every minute should be spent watching explanations.",
         "Use 8 minutes for diagrams, 25 for updates, and 7 for reviewing mistakes."),
        ("plan-forty-five", "a binary-search boundary practice block",
         "A focused 45-minute plan reserves time for recall, one or two problems, and reflection.",
         "A learner wants to practice binary-search boundary cases.",
         "The best plan attempts many unrelated topics.",
         "Use 7 minutes for invariants, 30 for two problems, and 8 for corrections."),
        ("plan-fifty", "a single-topic graph traversal practice block",
         "For 50 minutes, keep one topic and divide time among review, solving, and retry planning.",
         "A student needs graph traversal practice without topic switching.",
         "A productive session must cover the entire DSA syllabus.",
         "Review traversal state for 10 minutes, solve for 30, then analyze for 10."),
        ("plan-mistakes", "mistake-driven study planning",
         "A short plan should include time to explain mistakes and schedule a retry.",
         "A learner repeatedly makes off-by-one errors in array windows.",
         "Once an answer is seen, the problem never needs revisiting.",
         "Solve one window problem, classify the boundary mistake, and retry it later."),
        ("plan-new", "planning for a new DSA topic",
         "For a new topic, begin with the invariant and a tiny trace before a full problem.",
         "A beginner has not studied heaps before and has a short session.",
         "The first step should be a difficult timed contest problem.",
         "Learn heap order, trace two insertions, then attempt one basic question."),
        ("plan-review", "planning a DSA review session",
         "For review, use retrieval first, target a weak pattern, and finish with a mistake note.",
         "A student studied recursion last week and wants to check retention.",
         "Review means rereading every note before trying recall.",
         "Write the base-case rule from memory, trace one call tree, and correct mistakes."),
    )),
    *_family("local_workflow", (
        ("workflow-clone", "entering the cloned ByteSeed repository",
         "After cloning, change into the ByteSeed directory before running repository commands.",
         "PowerShell opens in the parent directory containing the clone.",
         "Repository commands work from every directory without a path.",
         "Run cd ByteSeed, then continue setup inside the project."),
        ("workflow-venv", "creating and activating the virtual environment",
         "Create it with python -m venv .venv and activate it with .\\.venv\\Scripts\\Activate.ps1.",
         "A clean clone has Python but no isolated dependencies.",
         "Installing every package globally is required.",
         "Activate .venv before installing project dependencies."),
        ("workflow-install", "installing development dependencies",
         "python -m pip install -e . -r requirements-dev.txt installs the editable package and test dependencies.",
         "The environment is active, but importing byteseed fails.",
         "Only installing the package without the development requirements is the complete test setup.",
         "Run python -m pip install -e . -r requirements-dev.txt from the repository root."),
        ("workflow-chat", "launching local terminal chat",
         "From the repository root, run python chat.py to start interactive chat.",
         "Setup is complete and the user wants the ordinary terminal interface.",
         "The launch command should repeat the script filename.",
         "Run python chat.py; chat chooses an available attention backend automatically."),
        ("workflow-manual", "selecting manual attention for chat",
         "python chat.py --attention-backend manual requests the reference attention path.",
         "A developer wants the educational manual implementation.",
         "Manual attention requires changing checkpoint weights.",
         "Run python chat.py --attention-backend manual; it changes execution, not weights."),
        ("workflow-cache", "enabling the optional chat KV cache",
         "python chat.py --kv-cache enables the inference-only cache for that request.",
         "A user wants to try cached autoregressive decoding locally.",
         "KV caching is always enabled and stored in checkpoints.",
         "Run python chat.py --kv-cache; cache state is temporary and off by default."),
        ("workflow-tests", "running the ByteSeed test suite",
         "Run python -m pytest -q from the repository environment.",
         "A focused code change is ready for local verification.",
         "Testing requires starting model training.",
         "python -m pytest -q runs the synthetic suite without a training run."),
        ("workflow-docs", "using ByteSeed's focused documentation",
         "Use the docs for training, evaluation, testing, and data-quality details before long work.",
         "A contributor needs exact commands beyond the quick start.",
         "The README is the only technical reference.",
         "Read the focused document for the guarded workflow before running it."),
    )),
    *_family("cuda_troubleshooting", (
        ("cuda-available", "checking torch.cuda.is_available()",
         "torch.cuda.is_available() reports whether the active PyTorch runtime can currently use CUDA.",
         "A script unexpectedly selects CPU on a machine with an NVIDIA card.",
         "torch.cuda.is_available is a boolean variable and needs no parentheses.",
         "Print torch.cuda.is_available() in the active interpreter."),
        ("cuda-build", "checking the installed PyTorch CUDA build",
         "Inspect torch.version.cuda; a null value commonly indicates a CPU-only PyTorch build.",
         "The driver exists, but Torch may lack CUDA support.",
         "An NVIDIA GPU guarantees every PyTorch wheel is CUDA-enabled.",
         "Check torch.version.cuda and compare the build with official installation guidance."),
        ("cuda-smi", "using nvidia-smi as a driver check",
         "nvidia-smi confirms the driver sees the GPU, but not that the active PyTorch build supports CUDA.",
         "The command lists a GPU while Torch still returns false.",
         "If nvidia-smi works, PyTorch CUDA must work.",
         "Check both the driver view and the PyTorch build and environment."),
        ("cuda-driver", "checking the NVIDIA driver",
         "A missing or incompatible NVIDIA driver can prevent CUDA use with a suitable PyTorch build.",
         "nvidia-smi is missing or reports a driver communication error.",
         "Only Python package changes can fix every CUDA problem.",
         "Verify a supported driver installation before changing model code."),
        ("cuda-environment", "checking the active Python environment",
         "Confirm the interpreter and environment because another environment may have a CPU-only Torch build.",
         "CUDA-enabled Torch was installed, but the project shell reports false.",
         "Every virtual environment shares the same PyTorch package.",
         "Print the interpreter path and Torch version from the shell launching ByteSeed."),
        ("cuda-reinstall", "installing a matching CUDA-enabled PyTorch build",
         "For a CPU-only build, use PyTorch's current official selector for a compatible CUDA build.",
         "torch.version.cuda is null after the environment is confirmed.",
         "Any random wheel containing CUDA is safe to install.",
         "Choose the documented build instead of guessing a package URL or CUDA version."),
        ("cuda-device", "checking the selected device",
         "After CUDA is available, verify the application selects cuda rather than an explicit cpu device.",
         "Torch sees CUDA, but tensors remain on CPU.",
         "CUDA availability automatically moves every tensor.",
         "Inspect the resolved device and keep model and input tensors together."),
        ("cuda-fallback", "using the CPU fallback",
         "ByteSeed can run on CPU when CUDA is unavailable, although speed depends on the workload.",
         "A learner cannot resolve GPU access but wants a small correctness test.",
         "ByteSeed refuses all CPU execution.",
         "Use CPU for the test and investigate driver or build issues separately."),
    )),
    *_family("checkpoint_git_hygiene", (
        ("checkpoint-ignore", "ignoring generated checkpoints",
         "Generated checkpoint binaries normally belong in .gitignore, not ordinary source commits.",
         "A new .pt file appears after a local run.",
         "Every generated model file should be committed with Python source.",
         "Keep the binary out while preserving the code and configuration."),
        ("checkpoint-storage", "storing checkpoints outside ordinary Git history",
         "Use release assets, a model registry, object storage, or an artifact service for distribution.",
         "Collaborators need a large trained weight file.",
         "The only way to share weights is a normal Git commit.",
         "Publish the artifact separately and document its version and digest."),
        ("checkpoint-source", "distinguishing source from model artifacts",
         "Source and small configuration belong in Git; large generated weights are versioned artifacts.",
         "A review contains Python changes plus hundreds of megabytes of weights.",
         "Generated weights and source have identical version-control needs.",
         "Review source in Git and reference separately stored weights."),
        ("checkpoint-unstage", "handling an accidentally staged checkpoint",
         "Remove an accidentally staged checkpoint from the index before committing and confirm the ignore rule.",
         "git status shows a generated .pt file staged.",
         "Deleting the entire repository is the safest correction.",
         "Unstage only the artifact, keep it locally if needed, and verify the source diff."),
        ("checkpoint-provenance", "recording checkpoint provenance",
         "Shared checkpoints need kind, configuration, tokenizer/data identity, and a digest when available.",
         "Two similarly named weights came from different runs.",
         "A filename alone is complete provenance.",
         "Versioned metadata and digests distinguish the intended artifact."),
        ("checkpoint-name", "avoiding invented checkpoint filenames",
         "Refer to a selected checkpoint or user path instead of inventing a file that may not exist.",
         "A user asks for a saved model without listing artifacts.",
         "Always claim final_model_best.pt exists.",
         "Ask for or inspect the real path before giving a file-specific command."),
        ("checkpoint-release", "the nuance of checkpoint distribution",
         "Git hosting is not forbidden, but generated weights should stay out of ordinary source history.",
         "A maintainer wants a public release with downloadable weights.",
         "No checkpoint may ever be associated with Git hosting.",
         "A release asset can be appropriate while repository history excludes the binary."),
        ("checkpoint-review", "reviewing artifacts before a commit",
         "Inspect git status and the diff so checkpoints, runs, and tokenizer binaries are not included accidentally.",
         "An experiment left several new files around the working tree.",
         "A successful run means every new file belongs in the commit.",
         "Keep only intended source, tests, and documentation changes in scope."),
    )),
)


CLUSTER_OVERRIDES = {
    "stack-push": "stack-push-pop",
    "stack-pop": "stack-push-pop",
    "queue-enqueue": "queue-operations",
    "queue-dequeue": "queue-operations",
    "queue-front": "queue-operations",
}


def lesson_cluster_id(lesson: Lesson) -> str:
    """Return a stable semantic cluster independent of generated record order."""

    return CLUSTER_OVERRIDES.get(lesson.lesson_id, lesson.lesson_id)


def render_prompt(lesson: Lesson, prompt_form: str) -> str:
    if prompt_form == "direct_definition":
        return f"Explain {lesson.focus} in plain language."
    if prompt_form == "scenario":
        return f"{lesson.situation} What is the correct conclusion?"
    if prompt_form == "comparison":
        return f"Contrast {lesson.focus} with this mistaken view: {lesson.misconception}"
    if prompt_form == "misconception_correction":
        return f'A beginner says, "{lesson.misconception}" Correct the claim briefly.'
    if prompt_form == "why":
        return f"Why does {lesson.focus} matter here? {lesson.situation}"
    if prompt_form == "how":
        return f"How should someone apply {lesson.focus} here? {lesson.situation}"
    if prompt_form == "command_oriented":
        return f"Give short, action-oriented guidance about {lesson.focus}. {lesson.situation}"
    if prompt_form == "example_request":
        return f"Give a concrete example that demonstrates {lesson.focus}."
    raise ValueError(f"unknown prompt form: {prompt_form!r}")


def render_response(lesson: Lesson, prompt_form: str) -> str:
    if prompt_form in {"scenario", "how", "command_oriented", "example_request"}:
        return lesson.example
    if prompt_form in {"comparison", "misconception_correction"}:
        return f"That view is incorrect. {lesson.fact}"
    if prompt_form == "why":
        return f"{lesson.fact} This keeps the answer tied to the actual behavior."
    if prompt_form == "direct_definition":
        return lesson.fact
    raise ValueError(f"unknown prompt form: {prompt_form!r}")
